name: library_management
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  shared_preferences:
  flutter_animate:
  flutter_launcher_icons:
  provider:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
flutter_icons:
  android: true
  ios: true
  image_path: assets/splash.png
flutter:
  uses-material-design: true

  assets:
    - assets/splash.gif
    - assets/splash.png
